# Generated by Django 6.0.6 on 2026-07-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNOLOGIST', 'Laboratory Technologist'), ('RADIOLOGIST', 'Radiologist'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant'), ('MORTUARY_ATTENDANT', 'Mortuary Attendant'), ('HR_OFFICER', 'HR Officer'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('AMBULANCE_DISPATCHER', 'Ambulance Dispatcher')], max_length=30),
        ),
    ]
