# Generated by Django 6.0.6 on 2026-07-24 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_payments_processed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_payments', to='api.patient')),
            ],
            options={
                'db_table': 'bulk_payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkPaymentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bulk_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.bulkpayment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_payment_lines', to='api.invoice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_payment_line', to='api.payment')),
            ],
            options={
                'db_table': 'bulk_payment_lines',
            },
        ),
    ]
