# Generated by Django 6.0.6 on 2026-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bulkpayment_bulkpaymentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
