# Generated by Django 6.0.6 on 2026-07-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='insurance_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price billed when this dispense is paid via insurance. Falls back to unit_price if not set.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispense',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacydispense',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacydispense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('INSURANCE', 'Insurance')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacydispense',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Prepared — Awaiting Payment'), ('COMPLETED', 'Completed — Stock Deducted'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacydispense',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='api.medicinebatch'),
        ),
    ]
