# Generated by Django 6.0.6 on 2026-08-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='coding_correction_notes',
            field=models.TextField(blank=True, help_text='If HIM corrected the code, what changed and why.'),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='coding_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='coding_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_coding_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='is_coding_verified',
            field=models.BooleanField(default=False),
        ),
    ]
