# Generated by Django 6.0.6 on 2026-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNOLOGIST', 'Laboratory Technologist'), ('RADIOLOGIST', 'Radiologist'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant'), ('MORTUARY_ATTENDANT', 'Mortuary Attendant'), ('HR_OFFICER', 'HR Officer'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('AMBULANCE_DISPATCHER', 'Ambulance Dispatcher'), ('HEALTH_RECORDS_OFFICER', 'Health Records Officer'), ('MEDICAL_RECORDS_OFFICER', 'Medical Records Officer'), ('BIOMEDICAL_ENGINEER', 'Biomedical Engineer'), ('IT_SUPPORT_OFFICER', 'IT Support Officer')], max_length=30),
        ),
    ]
