# Generated by Django 6.1 on 2026-08-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_department_head_of_department'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="This user's primary/home branch. GROUP_ADMIN users may leave this null since they operate across all branches.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GROUP_ADMIN', 'Group Admin / Owner'), ('SUPER_ADMIN', 'Super Admin'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECHNOLOGIST', 'Laboratory Technologist'), ('RADIOLOGIST', 'Radiologist'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant'), ('MORTUARY_ATTENDANT', 'Mortuary Attendant'), ('HR_OFFICER', 'HR Officer'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('AMBULANCE_DISPATCHER', 'Ambulance Dispatcher'), ('HEALTH_RECORDS_OFFICER', 'Health Records Officer'), ('MEDICAL_RECORDS_OFFICER', 'Medical Records Officer'), ('BIOMEDICAL_ENGINEER', 'Biomedical Engineer'), ('IT_SUPPORT_OFFICER', 'IT Support Officer')], max_length=30),
        ),
    ]
