# Generated by Django 6.1 on 2026-08-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_branch_alter_user_role'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(help_text='Denormalized from visit.branch for fast revenue reporting without a join — set automatically whenever an invoice is created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_branch',
            field=models.ForeignKey(blank=True, help_text='Where this patient was first registered. The patient RECORD is group-wide and visible/searchable at any branch — this field is informational only, not an access restriction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_registered', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='visit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='branches.branch'),
        ),
    ]
