# Generated by Django 6.1 on 2026-08-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_invoice_branch_patient_home_branch_payment_branch_and_more'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinebatch',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Physical stock location. Each branch's pharmacy stock is separate — a batch received at one branch is never dispensed from another.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_batches', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='otcsale',
            name='branch',
            field=models.ForeignKey(help_text="Set automatically from the serving cashier's branch — walk-in stock is drawn from this branch's batches.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otc_sales', to='branches.branch'),
        ),
    ]
