# Generated by Django 6.1 on 2026-08-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_medicinebatch_branch_otcsale_branch'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpayment',
            name='branch',
            field=models.ForeignKey(help_text='Denormalized from the invoices being paid — every invoice in a single bulk payment belongs to the same branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_payments', to='branches.branch'),
        ),
    ]
