# Generated by Django 6.1 on 2026-08-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bulkpayment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpayment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/bulk_qr/'),
        ),
    ]
