# Generated by Django 6.1 on 2026-08-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bulkpayment_qr_code'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch this department belongs to. A department name can repeat across branches (e.g. 'ICU / HDU' exists separately at each hospital) but must be unique within one branch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'branch')},
        ),
    ]
