# Generated by Django 6.0.6 on 2026-08-04 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('CUSTOM', 'Custom')], default='STARTER', max_length=20)),
                ('license_key', models.CharField(blank=True, help_text='Reference/identifier for this license agreement.', max_length=100)),
                ('max_beds', models.PositiveIntegerField(default=20, help_text='Total across inpatient + ICU/HDU beds combined.')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Total active staff accounts across all roles.')),
                ('licensed_to', models.CharField(blank=True, help_text='Facility/organization name on the license.', max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating this suspends new bed/user creation without deleting existing data.')),
                ('notes', models.TextField(blank=True)),
                ('updated_at_display', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facility_license',
            },
        ),
    ]
