# Generated by Django 6.0.6 on 2026-08-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylicense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facilitylicense',
            name='license_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitylicense',
            name='licensed_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
