# Generated by Django 6.1 on 2026-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_facilitylicense_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylicense',
            name='max_patients',
            field=models.PositiveIntegerField(default=5000, help_text='Maximum total unique patient records this license permits across the whole group/facility.'),
        ),
    ]
