"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-ehv6%k&)3gc2dav3$k^d^m(#i5wa#po)@bp=2cn0@(xhasz_g!",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # Third party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "drf_spectacular",

    # Local
    "api",
    "inpatient",
    "mch",
    "emergency",
    "insurance",
    "etims",
    "assets",
    "procurement",
    "hr",
    "ambulance",
    "mortuary",
    "theatre",
    "finance",
    "bloodbank",
    "dental",
    "eyeclinic",
    "dialysis",
    "icu",
    "security",
    "stockcontrol",
    "leakage",
    "executive",
    "insights",
    "messaging",
    "notifications",
    "medrecords",
    "biomed",
    "communication",
    "tickets",
    "licensing",
    "moh",
    "support",
    "pacs",
    "doctormgmt",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.AuditLogMiddleware",  # captures request.user + IP for signals
    "security.middleware.LoginRateLimitMiddleware",
    "security.middleware.SessionIdleTimeoutMiddleware",
]


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_USER_MODEL = "api.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    #{"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# DRF / JWT / Filtering / Docs
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "EXCEPTION_HANDLER": "api.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=8),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "HMIS API",
    "DESCRIPTION": "Hospital Management Information System - REST API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://192.168.0.174:3000",
    "http://172.19.144.1:3000",
]


CORS_ALLOW_CREDENTIALS = True

# Hospital branding used on receipts / PDFs
HOSPITAL_NAME = config("HOSPITAL_NAME", default="City General Hospital")
HOSPITAL_LOGO_PATH = BASE_DIR / "static" / "logo.png"

SHA_ENVIRONMENT = config("SHA_ENVIRONMENT", default="sandbox")  # "sandbox" | "production"
SHA_API_BASE_URL = config("SHA_API_BASE_URL", default="")
SHA_API_KEY = config("SHA_API_KEY", default="")
SHA_FACILITY_CODE = config("SHA_FACILITY_CODE", default="")

ETIMS_ENVIRONMENT = config("ETIMS_ENVIRONMENT", default="sandbox")  # "sandbox" | "production"
ETIMS_API_BASE_URL = config("ETIMS_API_BASE_URL", default="")
ETIMS_API_KEY = config("ETIMS_API_KEY", default="")
ETIMS_KRA_PIN = config("ETIMS_KRA_PIN", default="")
ETIMS_BRANCH_ID = config("ETIMS_BRANCH_ID", default="00")
ETIMS_CU_SERIAL = config("ETIMS_CU_SERIAL", default="")

SECURITY_ADMIN_EMAIL = config("SECURITY_ADMIN_EMAIL", default="admin@yourhospital.com")

# Email backend — configure real SMTP in production; console backend is fine for dev
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@yourhospital.com")

MEDICORE_CONFIRM_EMAIL = config("MEDICORE_CONFIRM_EMAIL")
MEDICORE_CONFIRM_PASSWORD_HASH = config("MEDICORE_CONFIRM_PASSWORD_HASH")


# settings.py — the mode switch for when you're ready for real equipment
PACS_MODE = config("PACS_MODE", default="DEMO")  # "DEMO" or "REAL"
PACS_ORTHANC_BASE_URL = config("PACS_ORTHANC_BASE_URL", default="")
PACS_ORTHANC_USERNAME = config("PACS_ORTHANC_USERNAME", default="")
PACS_ORTHANC_PASSWORD = config("PACS_ORTHANC_PASSWORD", default="")