# Generated by Django 6.1 on 2026-08-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch this employee works at. Set automatically from the registering HR officer's branch.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='branch',
            field=models.ForeignKey(help_text='This payroll run only covers employees at this branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='branches.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('period_month', 'period_year', 'branch')},
        ),
    ]
