# Generated by Django 6.0.6 on 2026-07-31 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_consultationprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakageScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('new_leaks_found', models.PositiveIntegerField(default=0)),
                ('total_open_leaks', models.PositiveIntegerField(default=0)),
                ('total_leaked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_scans_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leakage_scan_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueLeakageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PHARMACY_DISPENSE', 'Pharmacy Dispense'), ('CONSULTATION_PROCEDURE', 'Consultation Procedure'), ('THEATRE', 'Theatre / Surgery'), ('DENTAL', 'Dental Procedure'), ('EYE_CLINIC', 'Eye Clinic Procedure'), ('MCH_DELIVERY', 'MCH Delivery'), ('MCH_IMMUNIZATION', 'MCH Immunization'), ('DIALYSIS', 'Dialysis Session'), ('ICU_PROCEDURE', 'ICU Procedure'), ('ICU_BED', 'ICU Bed Charge'), ('INPATIENT_BED', 'Inpatient Bed Charge'), ('BLOOD_BANK', 'Blood Unit Issue'), ('AMBULANCE', 'Ambulance Dispatch'), ('MORTUARY', 'Mortuary Service')], max_length=30)),
                ('source_object_id', models.UUIDField(help_text='PK of the underlying record (LabOrder, PharmacyDispense, etc.)')),
                ('patient_name', models.CharField(max_length=150)),
                ('hospital_number', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Unbilled — Open'), ('RESOLVED', 'Resolved — Invoice Created'), ('WRITTEN_OFF', 'Written Off (Justified)')], default='OPEN', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('write_off_reason', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leakage_records_resolved', to=settings.AUTH_USER_MODEL)),
                ('resolved_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_leakage_records', to='api.invoice')),
            ],
            options={
                'db_table': 'revenue_leakage_records',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['status', 'source_type'], name='revenue_lea_status_d96445_idx'), models.Index(fields=['event_date'], name='revenue_lea_event_d_52a30b_idx')],
                'unique_together': {('source_type', 'source_object_id')},
            },
        ),
    ]
