# Generated by Django 6.0.6 on 2026-07-19 20:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('emergency', '0001_initial'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        ('mch', '0002_deliverycharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortuaryServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mortuary_service_catalog',
            },
        ),
        migrations.CreateModel(
            name='MortuaryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('compartment_number', models.CharField(max_length=20, unique=True)),
                ('daily_storage_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mortuary_units',
            },
        ),
        migrations.CreateModel(
            name='MortuaryAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('deceased_name_freetext', models.CharField(blank=True, help_text="Used when there's no Patient record (e.g. unidentified BID case).", max_length=150)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_death', models.DateTimeField()),
                ('cause_of_death', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('INPATIENT', 'Inpatient Ward'), ('EMERGENCY', 'Emergency Department'), ('MCH', 'Maternal & Child Health'), ('BROUGHT_IN_DEAD', 'Brought in Dead (BID)'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('brought_by', models.CharField(blank=True, help_text='Who delivered the body, e.g. ambulance crew, police, family.', max_length=150)),
                ('police_ob_number', models.CharField(blank=True, help_text='Occurrence Book number, for BID / suspicious death cases.', max_length=60)),
                ('status', models.CharField(choices=[('ADMITTED', 'In Mortuary'), ('RELEASED', 'Released')], default='ADMITTED', max_length=20)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_case', to='inpatient.admission')),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_admissions_recorded', to=settings.AUTH_USER_MODEL)),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_case', to='mch.deliveryrecord')),
                ('emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_case', to='emergency.emergencyvisit')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_admissions', to='api.patient')),
                ('compartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='mortuary.mortuaryunit')),
            ],
            options={
                'db_table': 'mortuary_admissions',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('collector_name', models.CharField(max_length=150)),
                ('collector_id_number', models.CharField(blank=True, max_length=30)),
                ('collector_phone', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER_RELATIVE', 'Other Relative'), ('UNDERTAKER', 'Undertaker / Funeral Home'), ('POLICE', 'Police'), ('OTHER', 'Other')], max_length=20)),
                ('funeral_home', models.CharField(blank=True, max_length=150)),
                ('burial_permit_number', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_releases_processed', to=settings.AUTH_USER_MODEL)),
                ('mortuary_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='mortuary.mortuaryadmission')),
            ],
            options={
                'db_table': 'body_releases',
            },
        ),
        migrations.CreateModel(
            name='MortuaryCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortuary_charges', to='api.invoice')),
                ('mortuary_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='mortuary.mortuaryadmission')),
            ],
            options={
                'db_table': 'mortuary_charges',
                'ordering': ['created_at_display'],
            },
        ),
        migrations.CreateModel(
            name='MortuaryServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('COMPLETED', 'Completed')], default='ORDERED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_services', to='api.invoice')),
                ('mortuary_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mortuary.mortuaryadmission')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_services_ordered', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_services_performed', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='mortuary.mortuaryservicecatalog')),
            ],
            options={
                'db_table': 'mortuary_service_records',
            },
        ),
    ]
