# Generated by Django 6.1 on 2026-08-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('mortuary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortuaryunit',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this compartment physically belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mortuary_units', to='branches.branch'),
        ),
    ]
