# Generated by Django 6.0.6 on 2026-07-21 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialysisMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('machine_number', models.CharField(max_length=20, unique=True)),
                ('make_model', models.CharField(blank=True, max_length=150)),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dialysis_machines',
            },
        ),
        migrations.CreateModel(
            name='DialysisPatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('primary_diagnosis', models.TextField(blank=True, help_text='e.g. ESRD secondary to diabetic nephropathy.')),
                ('dry_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vascular_access_type', models.CharField(choices=[('AV_FISTULA', 'Arteriovenous (AV) Fistula'), ('AV_GRAFT', 'Arteriovenous (AV) Graft'), ('CENTRAL_CATHETER', 'Central Venous Catheter'), ('PERITONEAL', 'Peritoneal Dialysis Catheter')], default='AV_FISTULA', max_length=30)),
                ('access_site_notes', models.CharField(blank=True, max_length=255)),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=3)),
                ('session_duration_hours', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('dialyzer_type', models.CharField(blank=True, max_length=100)),
                ('anticoagulation_protocol', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred to Another Facility'), ('TRANSPLANTED', 'Received Transplant'), ('DECEASED', 'Deceased'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('started_on', models.DateField()),
                ('nephrologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialysis_profile', to='api.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_profiles_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dialysis_patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='DialysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed / No-Show'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pre_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('post_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pre_bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultrafiltration_target_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_flow_rate', models.PositiveSmallIntegerField(blank=True, help_text='ml/min', null=True)),
                ('dialysate_flow_rate', models.PositiveSmallIntegerField(blank=True, help_text='ml/min', null=True)),
                ('complications', models.TextField(blank=True)),
                ('nursing_notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_sessions', to='api.invoice')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='dialysis.dialysismachine')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialysis_sessions_performed', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dialysis.dialysispatientprofile')),
            ],
            options={
                'db_table': 'dialysis_sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VascularAccessCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('check_date', models.DateField()),
                ('thrill_present', models.BooleanField(blank=True, null=True)),
                ('bruit_present', models.BooleanField(blank=True, null=True)),
                ('signs_of_infection', models.BooleanField(default=False)),
                ('signs_of_stenosis', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vascular_access_checks', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_checks', to='dialysis.dialysispatientprofile')),
            ],
            options={
                'db_table': 'vascular_access_checks',
                'ordering': ['-check_date'],
            },
        ),
    ]
