# Generated by Django 6.0.6 on 2026-07-20 20:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('emergency', '0001_initial'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        ('mch', '0002_deliverycharge'),
        ('theatre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('donor_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('TEMPORARILY_DEFERRED', 'Temporarily Deferred'), ('PERMANENTLY_DEFERRED', 'Permanently Deferred')], default='ELIGIBLE', max_length=30)),
                ('deferral_reason', models.TextField(blank=True)),
                ('deferred_until', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donor_profile', to='api.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donors_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_donors',
            },
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('donation_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('hemoglobin_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_donations_collected', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bloodbank.blooddonor')),
            ],
            options={
                'db_table': 'blood_donations',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('patient_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('PACKED_RED_CELLS', 'Packed Red Cells (PRBC)'), ('PLATELETS', 'Platelets'), ('FRESH_FROZEN_PLASMA', 'Fresh Frozen Plasma (FFP)'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], default='WHOLE_BLOOD', max_length=30)),
                ('units_requested', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], default='ROUTINE', max_length=20)),
                ('clinical_indication', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CROSS_MATCHED', 'Cross-Matched'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected - Incompatible')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='inpatient.admission')),
                ('delivery_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='mch.deliveryrecord')),
                ('emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='emergency.emergencyvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='api.patient')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests_made', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='theatre.surgery')),
            ],
            options={
                'db_table': 'blood_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unit_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('PACKED_RED_CELLS', 'Packed Red Cells (PRBC)'), ('PLATELETS', 'Platelets'), ('FRESH_FROZEN_PLASMA', 'Fresh Frozen Plasma (FFP)'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], default='WHOLE_BLOOD', max_length=30)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('QUARANTINED', 'Quarantined (Pending Screening)'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='QUARANTINED', max_length=20)),
                ('screening_passed', models.BooleanField(blank=True, help_text='Null until screened.', null=True)),
                ('screening_notes', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='bloodbank.blooddonation')),
            ],
            options={
                'db_table': 'blood_units',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cross_match_compatible', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_issues', to='api.invoice')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_units_issued', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bloodbank.bloodrequest')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issue', to='bloodbank.bloodunit')),
            ],
            options={
                'db_table': 'blood_issues',
            },
        ),
    ]
