# Generated by Django 6.0.6 on 2026-07-17 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalizationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kra_pin', models.CharField(max_length=20)),
                ('branch_id', models.CharField(default='00', max_length=10)),
                ('cu_serial', models.CharField(blank=True, max_length=60)),
                ('default_vat_category', models.CharField(choices=[('A', 'A - Exempt (0%)'), ('B', 'B - Standard Rate (16%)'), ('C', 'C - Zero Rated (0%)'), ('D', 'D - Non-VATable'), ('E', 'E - Reduced Rate (8%)')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fiscalization_config',
            },
        ),
        migrations.CreateModel(
            name='FiscalizedReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FISCALIZED', 'Fiscalized'), ('FAILED', 'Failed'), ('VOIDED', 'Voided')], default='PENDING', max_length=20)),
                ('kra_invoice_number', models.CharField(blank=True, max_length=60)),
                ('cu_invoice_number', models.CharField(blank=True, help_text='Control Unit internal invoice number, if distinct from kra_invoice_number.', max_length=60)),
                ('qr_code_url', models.URLField(blank=True)),
                ('cu_signature', models.CharField(blank=True, max_length=255)),
                ('fiscalized_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('otc_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscalized_receipt', to='api.otcsale')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscalized_receipt', to='api.payment')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscalizations_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fiscalized_receipts',
            },
        ),
        migrations.CreateModel(
            name='FiscalizedReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_category', models.CharField(choices=[('A', 'A - Exempt (0%)'), ('B', 'B - Standard Rate (16%)'), ('C', 'C - Zero Rated (0%)'), ('D', 'D - Non-VATable'), ('E', 'E - Reduced Rate (8%)')], default='A', max_length=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='etims.fiscalizedreceipt')),
            ],
            options={
                'db_table': 'fiscalized_receipt_items',
            },
        ),
    ]
