# Generated by Django 6.0.6 on 2026-07-20 10:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('emergency', '0001_initial'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingTheatre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('theatre_number', models.CharField(max_length=20, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('CLEANING', 'Cleaning / Turnover'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'operating_theatres',
            },
        ),
        migrations.CreateModel(
            name='SurgicalProcedureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'surgical_procedure_catalog',
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('theatre_in_at', models.DateTimeField(auto_now_add=True)),
                ('incision_at', models.DateTimeField(blank=True, null=True)),
                ('closure_at', models.DateTimeField(blank=True, null=True)),
                ('theatre_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESSFUL', 'Successful'), ('COMPLICATIONS', 'Completed with Complications'), ('DECEASED', 'Patient Deceased')], max_length=20)),
                ('operative_notes', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('estimated_blood_loss_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='api.invoice')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries', to='theatre.operatingtheatre')),
            ],
            options={
                'db_table': 'surgeries',
            },
        ),
        migrations.CreateModel(
            name='PostOpNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consciousness_level', models.CharField(blank=True, max_length=100)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_op_notes_recorded', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_op_notes', to='theatre.surgery')),
            ],
            options={
                'db_table': 'post_op_notes',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theatre_usages', to='api.medicinebatch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theatre_consumables', to='api.invoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theatre_usages', to='api.medicine')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_recorded', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables_used', to='theatre.surgery')),
            ],
            options={
                'db_table': 'theatre_consumable_usage',
            },
        ),
        migrations.CreateModel(
            name='SurgeryBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('priority', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('URGENT', 'Urgent'), ('ELECTIVE', 'Elective')], default='ELECTIVE', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='REQUESTED', max_length=20)),
                ('requested_date', models.DateTimeField()),
                ('diagnosis', models.TextField(blank=True)),
                ('pre_op_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_bookings', to='inpatient.admission')),
                ('emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_bookings', to='emergency.emergencyvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bookings', to='api.patient')),
                ('primary_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_primary_surgeon', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_bookings_requested', to=settings.AUTH_USER_MODEL)),
                ('theatre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='theatre.operatingtheatre')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='theatre.surgicalprocedurecatalog')),
            ],
            options={
                'db_table': 'surgery_bookings',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.AddField(
            model_name='surgery',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='theatre.surgerybooking'),
        ),
        migrations.CreateModel(
            name='SurgicalTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('PRIMARY_SURGEON', 'Primary Surgeon'), ('ASSISTANT_SURGEON', 'Assistant Surgeon'), ('ANESTHETIST', 'Anesthetist'), ('SCRUB_NURSE', 'Scrub Nurse'), ('CIRCULATING_NURSE', 'Circulating Nurse'), ('OTHER', 'Other')], max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Billable professional fee for this role, if separately charged.', max_digits=10)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='theatre.surgery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surgical_team_members',
                'unique_together': {('surgery', 'user', 'role')},
            },
        ),
    ]
