# Generated by Django 6.0.6 on 2026-08-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_role'),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theatre_surgeries', to='api.visit'),
        ),
    ]
