# Generated by Django 6.0.6 on 2026-07-21 19:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICUBed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bed_number', models.CharField(max_length=20, unique=True)),
                ('unit_type', models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('HDU', 'High Dependency Unit'), ('NICU', 'Neonatal ICU'), ('PICU', 'Pediatric ICU')], default='ICU', max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_ventilator', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning / Turnover'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'icu_beds',
            },
        ),
        migrations.CreateModel(
            name='ICUProcedureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'icu_procedure_catalog',
            },
        ),
        migrations.CreateModel(
            name='ICUAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('icu_admission_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('admission_reason', models.CharField(choices=[('RESPIRATORY_FAILURE', 'Respiratory Failure'), ('SEPSIS', 'Sepsis / Septic Shock'), ('POST_SURGICAL', 'Post-Surgical Monitoring'), ('TRAUMA', 'Trauma'), ('CARDIAC', 'Cardiac Event'), ('NEUROLOGICAL', 'Neurological Event'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('admission_diagnosis', models.TextField(blank=True)),
                ('severity_score', models.PositiveSmallIntegerField(blank=True, help_text='e.g. APACHE II or SOFA score at admission.', null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'In ICU/HDU'), ('STEPPED_DOWN', 'Stepped Down to Ward'), ('DISCHARGED_HOME', 'Discharged Home'), ('DECEASED', 'Deceased'), ('TRANSFERRED_OUT', 'Transferred to Another Facility')], default='ADMITTED', max_length=20)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_admissions_recorded', to=settings.AUTH_USER_MODEL)),
                ('attending_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_admissions_attending', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icu_admissions', to='api.patient')),
                ('ward_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_episodes', to='inpatient.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='icu.icubed')),
            ],
            options={
                'db_table': 'icu_admissions',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ICUProcedureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('icu_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='icu.icuadmission')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_procedures', to='api.invoice')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_procedures_performed', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='icu.icuprocedurecatalog')),
            ],
            options={
                'db_table': 'icu_procedure_records',
            },
        ),
        migrations.CreateModel(
            name='ICUVitalsMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mean_arterial_pressure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gcs_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GCS Score')),
                ('urine_output_ml', models.PositiveIntegerField(blank=True, help_text='Per hour, ml.', null=True)),
                ('central_venous_pressure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('icu_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='icu.icuadmission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'icu_vitals_monitoring',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VentilatorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('NONE', 'Not Ventilated'), ('CPAP', 'CPAP'), ('BIPAP', 'BiPAP'), ('AC', 'Assist Control (AC)'), ('SIMV', 'SIMV'), ('PSV', 'Pressure Support (PSV)')], default='NONE', max_length=10)),
                ('fio2_percent', models.PositiveSmallIntegerField(blank=True, help_text='Fraction of inspired oxygen, %.', null=True)),
                ('peep_cmh2o', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PEEP (cmH2O)')),
                ('tidal_volume_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate_set', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peak_pressure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('icu_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventilator_settings', to='icu.icuadmission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventilator_settings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventilator_settings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ICUBedCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='icu.icubed')),
                ('icu_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_charges', to='icu.icuadmission')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icu_bed_charges', to='api.invoice')),
            ],
            options={
                'db_table': 'icu_bed_charges',
                'unique_together': {('icu_admission', 'charge_date')},
            },
        ),
    ]
