# Generated by Django 6.1 on 2026-08-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('icu', '0002_icuadmission_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='icubed',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this ICU/HDU bed physically belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icu_beds', to='branches.branch'),
        ),
    ]
