# Generated by Django 6.0.6 on 2026-07-19 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('ambulance_type', models.CharField(choices=[('BASIC', 'Basic Life Support (BLS)'), ('ADVANCED', 'Advanced Life Support (ALS)'), ('NEONATAL', 'Neonatal / ICU Transport'), ('PATIENT_TRANSPORT', 'Non-Emergency Patient Transport')], default='BASIC', max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Number of patients it can carry.')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat callout fee.', max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_CALL', 'On Call / Dispatched'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('patient_name_freetext', models.CharField(blank=True, help_text="Used when the patient isn't registered yet (unknown emergency pickup).", max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('dispatch_type', models.CharField(choices=[('EMERGENCY_PICKUP', 'Emergency Pickup'), ('INTER_FACILITY_TRANSFER', 'Inter-Facility Transfer'), ('DISCHARGE_TRANSPORT', 'Discharge Transport'), ('OTHER', 'Other')], default='EMERGENCY_PICKUP', max_length=30)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(default='Facility', max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('DISPATCHED', 'Dispatched / En Route to Pickup'), ('PATIENT_ONBOARD', 'Patient Onboard / En Route to Destination'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='ambulance.ambulance')),
                ('emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_dispatch', to='emergency.emergencyvisit')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_dispatches', to='api.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_dispatches', to='api.patient')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambulance_dispatches',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceMaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('SERVICE', 'Routine Service'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection')], default='SERVICE', max_length=20)),
                ('service_date', models.DateField()),
                ('odometer_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='ambulance.ambulance')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_maintenance_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambulance_maintenance_logs',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceCrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('DRIVER', 'Driver'), ('PARAMEDIC', 'Paramedic'), ('NURSE', 'Nurse')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='ambulance.ambulance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_crew_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambulance_crew_members',
                'unique_together': {('ambulance', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DispatchCrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('DRIVER', 'Driver'), ('PARAMEDIC', 'Paramedic'), ('NURSE', 'Nurse')], max_length=20)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='ambulance.ambulancedispatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches_crewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatch_crew_members',
                'unique_together': {('dispatch', 'user')},
            },
        ),
    ]
