# Generated by Django 6.1 on 2026-08-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bulkpayment_branch'),
        ('branches', '0001_initial'),
        ('finance', '0002_cashiershift_cashdrop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='branch',
            field=models.ForeignKey(help_text="This budget line only covers this branch's spend against this department.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='branch',
            field=models.ForeignKey(help_text="Set automatically from the cashier's own branch at shift open.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch incurred this expense. Set automatically from the submitting user's branch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch this journal entry belongs to. Set automatically from the posting user's branch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='branches.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('department', 'fiscal_period', 'branch')},
        ),
    ]
