from django.db import models
from api.models import BaseModel, User


class InsightSeverity(models.TextChoices):
    INFO = "INFO", "Informational"
    WARNING = "WARNING", "Warning"
    CRITICAL = "CRITICAL", "Critical"


class InsightCategory(models.TextChoices):
    REVENUE = "REVENUE", "Revenue"
    PHARMACY = "PHARMACY", "Pharmacy"
    STAFFING = "STAFFING", "Staffing / Doctor Behavior"
    INVENTORY = "INVENTORY", "Inventory"
    PATTERN = "PATTERN", "Recurring Pattern"
    THEFT = "THEFT", "Theft / Loss Suspected"


class BusinessInsight(BaseModel):
    """
    A single generated insight — plain-English statement plus the underlying
    numbers that produced it. Regenerated by a scheduled job; old insights
    that are no longer true (e.g. stock got restocked) are marked stale
    rather than deleted, preserving history for trend review.
    """
    category = models.CharField(max_length=20, choices=InsightCategory.choices)
    severity = models.CharField(max_length=20, choices=InsightSeverity.choices, default=InsightSeverity.INFO)
    headline = models.CharField(max_length=255)
    detail = models.TextField(blank=True)
    metrics = models.JSONField(default=dict, blank=True)
    is_stale = models.BooleanField(default=False)
    acknowledged_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="insights_acknowledged")
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "business_insights"
        ordering = ["-generated_at"]

    def __str__(self):
        return f"[{self.severity}] {self.headline}"