# Generated by Django 6.0.6 on 2026-08-04 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/')),
                ('announcement_type', models.CharField(choices=[('GENERAL', 'General Announcement'), ('TRAINING', 'Training / Event'), ('MAINTENANCE', 'System Maintenance'), ('POLICY', 'Policy Update'), ('EMERGENCY', 'Emergency / Critical Incident'), ('HR_NOTICE', 'HR Notice')], default='GENERAL', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of Role values. Empty = all staff.')),
                ('event_date', models.DateTimeField(blank=True, help_text='For training/events/maintenance — when the thing is actually happening.', null=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_in_app', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('email_failed_count', models.PositiveIntegerField(default=0)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at_display'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped — no email on file')], default='PENDING', max_length=20)),
                ('email_error', models.CharField(blank=True, max_length=255)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='communication.announcement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_receipts',
                'unique_together': {('announcement', 'recipient')},
            },
        ),
    ]
