# Generated by Django 6.1 on 2026-08-15 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text="Short code used in patient/invoice numbering, e.g. 'NRB', 'MSA'.", max_length=20, unique=True)),
                ('level', models.CharField(choices=[('LEVEL_2', 'Level 2 (Dispensary)'), ('LEVEL_3', 'Level 3 (Health Centre)'), ('LEVEL_4', 'Level 4 (Sub-County Hospital)'), ('LEVEL_5', 'Level 5 (County/Referral Hospital)'), ('CLINIC', 'Clinic')], default='LEVEL_4', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kra_pin', models.CharField(blank=True, help_text="Branch's own KRA PIN, if eTIMS is fiscalized per-branch rather than group-wide.", max_length=20)),
                ('sha_facility_code', models.CharField(blank=True, max_length=50)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Optional — for temporary cover, e.g. a locum's contract end date.", null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='branches.branch')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_branch_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'branch_staff_assignments',
                'unique_together': {('user', 'branch')},
            },
        ),
    ]
