# Generated by Django 6.0.6 on 2026-07-16 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('insurer_type', models.CharField(choices=[('SHA', 'Social Health Authority (SHA)'), ('PRIVATE', 'Private Insurer')], default='PRIVATE', max_length=20)),
                ('requires_preauth', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'insurers',
            },
        ),
        migrations.CreateModel(
            name='PatientInsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_number', models.CharField(max_length=60)),
                ('scheme_name', models.CharField(blank=True, max_length=150)),
                ('principal_member_name', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('OTHER', 'Other')], default='PRINCIPAL', max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insurer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='api.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_insurance_policies',
                'unique_together': {('patient', 'insurer', 'member_number')},
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gateway_reference', models.CharField(blank=True, help_text='SHA claim ID or insurer reference, once known.', max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='api.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='api.visit')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.patientinsurancepolicy')),
            ],
            options={
                'db_table': 'insurance_claims',
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField()),
                ('scheme_returned', models.CharField(blank=True, max_length=150)),
                ('member_status', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checks_run', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='insurance.patientinsurancepolicy')),
            ],
            options={
                'db_table': 'eligibility_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('benefit_code', models.CharField(blank=True, help_text='SHA benefit package code or insurer service code, if applicable.', max_length=60)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_items', to='api.invoice')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.insuranceclaim')),
            ],
            options={
                'db_table': 'claim_items',
                'unique_together': {('claim', 'invoice')},
            },
        ),
    ]
