# Generated by Django 6.1 on 2026-08-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Denormalized from the invoices being claimed — set automatically when the claim is filed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='branches.branch'),
        ),
    ]
