# Generated by Django 5.1.15 on 2026-08-12 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_department_head_of_department'),
        ('emergency', '0001_initial'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        ('mch', '0002_deliverycharge'),
        ('medrecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text="e.g. 'Diabetes Management', 'Post-Op Wound Care', 'Hypertension Monitoring'.", max_length=255)),
                ('condition', models.CharField(blank=True, help_text='Primary condition being managed, free text or ICD-10-linked via notes.', max_length=255)),
                ('source_type', models.CharField(choices=[('CONSULTATION', 'OPD Consultation'), ('DISCHARGE', 'Inpatient Discharge'), ('EMERGENCY', 'Emergency Visit'), ('DELIVERY', 'MCH Delivery'), ('REFERRAL', 'Referral'), ('MANUAL', 'Manually Created')], default='MANUAL', max_length=20)),
                ('is_chronic', models.BooleanField(default=False, help_text='Chronic disease requiring ongoing monitoring (diabetes, hypertension, HIV, etc.) vs. a one-off follow-up.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans_created', to=settings.AUTH_USER_MODEL)),
                ('icd10_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='api.icd10code')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='api.patient')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='api.department')),
                ('responsible_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans_responsible_for', to=settings.AUTH_USER_MODEL)),
                ('source_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='inpatient.admission')),
                ('source_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='api.consultation')),
                ('source_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='mch.deliveryrecord')),
                ('source_emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='emergency.emergencyvisit')),
                ('source_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to='medrecords.referral')),
            ],
            options={
                'db_table': 'care_plans',
                'ordering': ['-created_at_display'],
            },
        ),
        migrations.CreateModel(
            name='CareMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='carecoordination.careplan')),
            ],
            options={
                'db_table': 'care_milestones',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('CLINIC_REVIEW', 'Clinic Review Appointment'), ('PENDING_INVESTIGATION', 'Pending Investigation Result'), ('SPECIALIST_REVIEW', 'Pending Specialist Review'), ('REFERRAL_FOLLOWUP', 'Referral Follow-up'), ('POST_DISCHARGE_CHECK', 'Post-Discharge Check-in'), ('MEDICATION_REVIEW', 'Medication Review'), ('OUTREACH_CALL', 'Patient Outreach / Phone Call'), ('OTHER', 'Other')], default='CLINIC_REVIEW', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed — Patient Did Not Return'), ('CANCELLED', 'Cancelled'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='api.department')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='carecoordination.careplan')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks_escalated_to', to=settings.AUTH_USER_MODEL)),
                ('resulting_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_task_origin', to='api.visit')),
            ],
            options={
                'db_table': 'follow_up_tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ChronicMonitoringReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metric_name', models.CharField(help_text="e.g. 'Blood Glucose', 'Systolic BP', 'Weight'.", max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_readings', to='carecoordination.careplan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_readings_recorded', to=settings.AUTH_USER_MODEL)),
                ('follow_up_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings_taken', to='carecoordination.followuptask')),
            ],
            options={
                'db_table': 'chronic_monitoring_readings',
                'ordering': ['recorded_at'],
            },
        ),
    ]
