# Generated by Django 6.1 on 2026-08-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this ward physically belongs to. A bed can only ever be occupied by patients admitted at this branch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='branches.branch'),
        ),
    ]
