# Generated by Django 6.0.6 on 2026-08-01 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('REVENUE', 'Revenue'), ('PHARMACY', 'Pharmacy'), ('STAFFING', 'Staffing / Doctor Behavior'), ('INVENTORY', 'Inventory'), ('PATTERN', 'Recurring Pattern'), ('THEFT', 'Theft / Loss Suspected')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('headline', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_stale', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights_acknowledged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_insights',
                'ordering': ['-generated_at'],
            },
        ),
    ]
