# Generated by Django 6.0.6 on 2026-08-10 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facility_name', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(choices=[('TECHNICAL_SUPPORT', 'Technical Support'), ('BILLING_LICENSING', 'Billing / Licensing'), ('FEATURE_REQUEST', 'Feature Request'), ('TRAINING', 'Training Request'), ('GENERAL', 'General Inquiry')], default='GENERAL', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact_inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
