# Generated by Django 6.0.6 on 2026-07-21 08:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeProcedureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eye_procedure_catalog',
            },
        ),
        migrations.CreateModel(
            name='EyeTreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('eye', models.CharField(choices=[('OD', 'Right Eye (OD)'), ('OS', 'Left Eye (OS)'), ('BOTH', 'Both Eyes')], default='BOTH', max_length=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('planned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_plans_created', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='eyeclinic.eyeprocedurecatalog')),
            ],
            options={
                'db_table': 'eye_treatment_plans',
            },
        ),
        migrations.CreateModel(
            name='EyeProcedureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_procedures', to='api.invoice')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_procedures_performed', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_record', to='eyeclinic.eyetreatmentplan')),
            ],
            options={
                'db_table': 'eye_procedure_records',
            },
        ),
        migrations.CreateModel(
            name='EyeVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('ophthalmologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_visits_attended', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_visits', to='api.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_visits_registered', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_visits', to='api.visit')),
            ],
            options={
                'db_table': 'eye_visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='eyetreatmentplan',
            name='eye_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='eyeclinic.eyevisit'),
        ),
        migrations.CreateModel(
            name='EyeExamination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visual_acuity_od', models.CharField(blank=True, max_length=20, verbose_name='Visual Acuity (Right Eye - OD)')),
                ('visual_acuity_os', models.CharField(blank=True, max_length=20, verbose_name='Visual Acuity (Left Eye - OS)')),
                ('iop_od', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IOP (Right Eye - OD, mmHg)')),
                ('iop_os', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IOP (Left Eye - OS, mmHg)')),
                ('sphere_od', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylinder_od', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_od', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sphere_os', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylinder_os', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_os', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anterior_segment_notes', models.TextField(blank=True)),
                ('posterior_segment_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('examined_at', models.DateTimeField(auto_now_add=True)),
                ('examined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_examinations_conducted', to=settings.AUTH_USER_MODEL)),
                ('eye_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='eyeclinic.eyevisit')),
            ],
            options={
                'db_table': 'eye_examinations',
            },
        ),
        migrations.CreateModel(
            name='SpectaclePrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lens_type', models.CharField(choices=[('SINGLE_VISION', 'Single Vision'), ('BIFOCAL', 'Bifocal'), ('PROGRESSIVE', 'Progressive'), ('READING', 'Reading Only')], default='SINGLE_VISION', max_length=20)),
                ('sphere_od', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylinder_od', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_od', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('add_od', models.DecimalField(blank=True, decimal_places=2, help_text='Reading addition, for bifocal/progressive.', max_digits=4, null=True)),
                ('sphere_os', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylinder_os', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_os', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('add_os', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pupillary_distance_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('eye_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectacle_prescriptions', to='eyeclinic.eyevisit')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectacle_prescriptions', to='api.invoice')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectacle_prescriptions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spectacle_prescriptions',
            },
        ),
    ]
