# Generated by Django 6.0.6 on 2026-07-18 23:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('po_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('FULLY_RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('grn_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('delivery_note_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_recorded', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'goods_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('MEDICINE', 'Medicine / Drug'), ('ASSET', 'Asset / Equipment'), ('CONSUMABLE', 'General Consumable'), ('OTHER', 'Other')], default='MEDICINE', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='api.medicine')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, help_text='Required for medicines.', max_length=60)),
                ('expiry_date', models.DateField(blank=True, help_text='Required for medicines.', null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_receipt_item', to='assets.asset')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceipt')),
                ('medicine_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_receipts', to='api.medicinebatch')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='procurement.purchaseorderitem')),
            ],
            options={
                'db_table': 'goods_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requisition_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to PO'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='api.department')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('MEDICINE', 'Medicine / Drug'), ('ASSET', 'Asset / Equipment'), ('CONSUMABLE', 'General Consumable'), ('OTHER', 'Other')], default='MEDICINE', max_length=20)),
                ('description', models.CharField(help_text='Free-text item description, required for non-medicine items.', max_length=255)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='api.medicine')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition')),
            ],
            options={
                'db_table': 'requisition_items',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('supplier_invoice_ref', models.CharField(blank=True, help_text="Supplier's own invoice/reference number.", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='procurement.purchaseorder')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_recorded', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.supplier')),
            ],
            options={
                'db_table': 'supplier_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MPESA', 'M-Pesa'), ('CHEQUE', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_made', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.supplierinvoice')),
            ],
            options={
                'db_table': 'supplier_payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
