# Generated by Django 6.0.6 on 2026-08-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('stockcontrol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivered_by_company',
            field=models.CharField(blank=True, help_text='Courier/transport company, if different from the Supplier.', max_length=150),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivered_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivered_by_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='stockcontrol.storelocation'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_inspected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspection_notes',
            field=models.TextField(blank=True, help_text='Condition on arrival, packaging integrity, expiry dates checked, discrepancies noted.'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inspection_passed',
            field=models.BooleanField(blank=True, help_text='Null until inspected.', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='receiver_contact_phone',
            field=models.CharField(blank=True, help_text='Direct phone of the receiving staff member, in case not on their profile.', max_length=20),
        ),
    ]
