# Generated by Django 6.0.6 on 2026-08-07 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashiershift_cashdrop'),
        ('procurement', '0002_goodsreceipt_delivered_by_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequisition',
            old_name='approved_at',
            new_name='hod_approved_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text="The department's active fiscal-period budget this requisition draws against.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='category',
            field=models.CharField(choices=[('MEDICINE', 'Medicine / Pharmacy'), ('IT_EQUIPMENT', 'IT Equipment (Laptops, Printers, etc.)'), ('ASSET', 'General Asset / Equipment'), ('CONSTRUCTION', 'Construction / Renovation'), ('TENDER', 'Tender (Network Installation, Contracted Works)'), ('SERVICE', 'Service Contract'), ('CONSUMABLE', 'General Consumable'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_hod_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD_APPROVAL', 'Pending HOD Approval'), ('HOD_APPROVED', 'HOD Approved — With Procurement'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to PO'), ('CANCELLED', 'Cancelled')], default='PENDING_HOD_APPROVAL', max_length=25),
        ),
    ]
