# Generated by Django 6.0.6 on 2026-08-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_rename_approved_at_purchaserequisition_hod_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='description',
            field=models.CharField(help_text='Free-text item description — required for non-medicine items (laptops, tender scope, construction details, etc.).', max_length=255),
        ),
    ]
