# Generated by Django 6.1 on 2026-08-19 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('procurement', '0004_remove_requisitionitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch this PO is for. Inherited from the linked requisition if present, otherwise set from the creating user's own branch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Which branch is raising this requisition. Set automatically from the requester's own branch.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='branches.branch'),
        ),
    ]
