# Generated by Django 6.0.6 on 2026-07-16 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_invoice_source_type'),
        ('inpatient', '0004_procedurecatalog_inpatientprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bay_number', models.CharField(max_length=20, unique=True)),
                ('zone', models.CharField(choices=[('TRIAGE', 'Triage'), ('RESUSCITATION', 'Resuscitation'), ('GENERAL', 'General ED'), ('OBSERVATION', 'Observation')], default='GENERAL', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning / Turnover')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emergency_bays',
            },
        ),
        migrations.CreateModel(
            name='EmergencyProcedureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emergency_procedure_catalog',
            },
        ),
        migrations.CreateModel(
            name='EmergencyMedicationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('OTHER', 'Other')], default='IV', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_orders', to='api.medicine')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_medication_orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_medication_orders',
            },
        ),
        migrations.CreateModel(
            name='EmergencyMedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GIVEN', 'Given'), ('MISSED', 'Missed'), ('REFUSED', 'Refused')], default='GIVEN', max_length=20)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_medications_administered', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_administrations', to='api.medicinebatch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_administrations', to='api.invoice')),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='emergency.emergencymedicationorder')),
            ],
            options={
                'db_table': 'emergency_medication_administrations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('triage_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Resuscitation (Immediate)'), (2, '2 - Emergent (< 10 min)'), (3, '3 - Urgent (< 30 min)'), (4, '4 - Less Urgent (< 60 min)'), (5, '5 - Non-Urgent')], null=True)),
                ('arrival_mode', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('AMBULANCE', 'Ambulance'), ('POLICE', 'Police'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_ED', 'In Emergency Department'), ('ADMITTED', 'Admitted to Ward'), ('DISCHARGED', 'Discharged Home'), ('TRANSFERRED_OUT', 'Transferred to Another Facility'), ('LAMA', 'Left Against Medical Advice'), ('DECEASED', 'Deceased')], default='IN_ED', max_length=20)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('disposition_at', models.DateTimeField(blank=True, null=True)),
                ('disposition_notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to='inpatient.admission')),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits_attending', to=settings.AUTH_USER_MODEL)),
                ('bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to='emergency.emergencybay')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_visits', to='api.patient')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits_registered', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to='api.visit')),
            ],
            options={
                'db_table': 'emergency_visits',
            },
        ),
        migrations.CreateModel(
            name='EmergencyProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_procedures', to='api.invoice')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_procedures_ordered', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_procedures_performed', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='emergency.emergencyprocedurecatalog')),
                ('emergency_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'emergency_procedures',
            },
        ),
        migrations.CreateModel(
            name='EmergencyNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('emergency_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'emergency_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='emergencymedicationorder',
            name='emergency_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='emergency.emergencyvisit'),
        ),
        migrations.CreateModel(
            name='EmergencyBayCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('hours_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='emergency.emergencybay')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_bay_charges', to='api.invoice')),
                ('emergency_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bay_charges', to='emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'emergency_bay_charges',
            },
        ),
        migrations.CreateModel(
            name='TriageVitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gcs_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GCS Score')),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pain Score (0-10)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='emergency.emergencyvisit')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'triage_vitals',
            },
        ),
    ]
