# Generated by Django 6.0.6 on 2026-08-03 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_tag', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('THERAPEUTIC', 'Therapeutic'), ('LIFE_SUPPORT', 'Life Support'), ('LABORATORY', 'Laboratory'), ('IMAGING', 'Imaging'), ('STERILIZATION', 'Sterilization'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, help_text='Physical location/department, e.g. ICU, Theatre 1, Radiology.', max_length=150)),
                ('risk_class', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk (Life-Critical)')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('DECOMMISSIONED', 'Decommissioned'), ('AWAITING_PARTS', 'Awaiting Parts')], default='OPERATIONAL', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('preventive_maintenance_interval_days', models.PositiveSmallIntegerField(default=90, help_text='How often this equipment needs routine preventive maintenance.')),
                ('calibration_interval_days', models.PositiveSmallIntegerField(blank=True, help_text="Leave blank if this equipment doesn't require calibration.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_registered', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_equipment', to='api.supplier')),
            ],
            options={
                'db_table': 'biomed_equipment',
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed — Out of Tolerance'), ('OVERDUE', 'Overdue')], default='SCHEDULED', max_length=20)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('reference_standard', models.CharField(blank=True, help_text='What standard/reference device was used.', max_length=150)),
                ('result_notes', models.TextField(blank=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_performed', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='biomed.equipment')),
            ],
            options={
                'db_table': 'biomed_calibrations',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_contact', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_details', models.TextField(blank=True)),
                ('annual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ManyToManyField(related_name='service_contracts', to='biomed.equipment')),
            ],
            options={
                'db_table': 'biomed_service_contracts',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency (Life-Critical Down)')], default='ROUTINE', max_length=20)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('caused_downtime', models.BooleanField(default=True, help_text='Uncheck if the equipment stayed operational despite this issue.')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='biomed.equipment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'biomed_service_requests',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective')], default='PREVENTIVE', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('work_done', models.TextField(blank=True)),
                ('parts_used', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='biomed.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, help_text='Set for corrective maintenance triggered by a service request; null for scheduled preventive maintenance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='biomed.servicerequest')),
            ],
            options={
                'db_table': 'biomed_maintenance_records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=2)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compatible_equipment', models.ManyToManyField(blank=True, related_name='compatible_spare_parts', to='biomed.equipment')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomed_spare_parts', to='api.supplier')),
            ],
            options={
                'db_table': 'biomed_spare_parts',
            },
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used_records', to='biomed.maintenancerecord')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='biomed.sparepart')),
            ],
            options={
                'db_table': 'biomed_spare_part_usage',
            },
        ),
    ]
