# Generated by Django 6.0.6 on 2026-08-10 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_department_head_of_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('series_instance_uid', models.CharField(editable=False, max_length=128, unique=True)),
                ('series_number', models.PositiveIntegerField(default=1)),
                ('series_description', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(choices=[('CR', 'Computed Radiography (X-Ray)'), ('CT', 'Computed Tomography'), ('MR', 'Magnetic Resonance'), ('US', 'Ultrasound'), ('MG', 'Mammography'), ('DX', 'Digital Radiography'), ('OT', 'Other')], default='OT', max_length=10)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pacs_series',
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sop_instance_uid', models.CharField(editable=False, max_length=128, unique=True)),
                ('instance_number', models.PositiveIntegerField(default=1)),
                ('file', models.ImageField(blank=True, help_text='Demo mode: a real preview image file. Production: may be left blank in favor of external_reference if images are served directly by the PACS server.', null=True, upload_to='pacs/images/%Y/%m/')),
                ('external_reference', models.CharField(blank=True, help_text='Production: WADO-URI or PACS-native retrieval URL for this instance, when images are served by an external DICOM server rather than stored in Django media.', max_length=500)),
                ('is_simulated', models.BooleanField(default=True, help_text='True for demo/mock images. False once real modality integration is connected.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pacs.series')),
            ],
            options={
                'db_table': 'pacs_images',
                'ordering': ['instance_number'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('study_instance_uid', models.CharField(editable=False, max_length=128, unique=True)),
                ('accession_number', models.CharField(editable=False, help_text='RIS-side order reference, matches DICOM AccessionNumber.', max_length=30, unique=True)),
                ('modality', models.CharField(choices=[('CR', 'Computed Radiography (X-Ray)'), ('CT', 'Computed Tomography'), ('MR', 'Magnetic Resonance'), ('US', 'Ultrasound'), ('MG', 'Mammography'), ('DX', 'Digital Radiography'), ('OT', 'Other')], default='OT', max_length=10)),
                ('description', models.CharField(blank=True, help_text="Study description, e.g. 'Chest X-Ray PA', 'CT Abdomen with Contrast'.", max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Images Received'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('study_date', models.DateTimeField(blank=True, help_text='When the exam was actually performed — set when images are received.', null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('DEMO', 'Demo / Simulated'), ('REAL_MODALITY', 'Real Modality (DICOM)')], default='DEMO', help_text="Marks whether this study's images came from the mock gateway or a real connected modality — kept visible in the UI so nobody mistakes demo data for a real patient study once real equipment is connected.", max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacs_studies', to='api.patient')),
                ('performing_technologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_studies_performed', to=settings.AUTH_USER_MODEL)),
                ('radiology_order', models.ForeignKey(blank=True, help_text='Links back to the existing RIS order in the radiology app, if this study originated from one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_study', to='api.radiologyorder')),
                ('referring_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacs_studies_referred', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pacs_studies',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_set', to='pacs.study'),
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('ADDENDUM', 'Addendum')], default='DRAFT', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_display', models.DateTimeField(auto_now_add=True)),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacs_reports_authored', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='pacs.study')),
            ],
            options={
                'db_table': 'pacs_reports',
            },
        ),
    ]
